CONFIG_VIDEO=y
CONFIG_SHELL=y
CONFIG_DEVICE_SHELL=y
CONFIG_PRINTK=y
CONFIG_LOG=y
CONFIG_DISPLAY=y
CONFIG_REQUIRES_FLOAT_PRINTF=y
CONFIG_LOG_MODE_DEFERRED=y
CONFIG_I2C_SHELL=y


### N6 Setting
CONFIG_VIDEO_BUFFER_POOL_NUM_MAX=1
CONFIG_VIDEO_BUFFER_POOL_SZ_MAX=80000
CONFIG_VIDEO_FRAME_WIDTH=160
CONFIG_VIDEO_FRAME_HEIGHT=120
CONFIG_VIDEO_PIXEL_FORMAT="RGBP"
CONFIG_MAIN_STACK_SIZE=2048
CONFIG_VIDEO_STM32_DCMIPP_SENSOR_PIXEL_FORMAT="pBAA"
CONFIG_VIDEO_STM32_DCMIPP_SENSOR_WIDTH=3280
CONFIG_VIDEO_STM32_DCMIPP_SENSOR_HEIGHT=2464
